### ISSUE TITLE
Добавить "Dereferencing"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#10]

**Comment by ilyakmet** [comment]
Наверно надо закрыть?

**Comment by funkill** [comment]
В PR'e сейчас перевод - разыменование ссылки. Кмк, он должен быть более общий - разыменование.
Н-р: "defererencing NULL pointer" будет лучше звучать в переводе как "разыменование нулевого указателя", а не "разыменование ссылки на нулевой указатель".

**Comment by ava57r** [comment]
хорошо
