### ISSUE TITLE
Добавить "Regular Methods"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#11]
Easy Rust: "Regular methods: these take self (or &self or &mut self). Regular methods use a . (a period). .clone() is an example of a regular method."

**Comment by funkill** [comment]
"Обычный метод". Не думаю, что стоит включать это в словарь, т.к. согласно официально документации он зовётся просто "метод", да и в "Easy Rust" в таком виде оно используется только в одном месте

https://doc.rust-lang.org/reference/items/associated-items.html#associated-functions-and-methods

**Comment by ava57r** [comment]
может для явности и добавим "метод"?

**Comment by ava57r** [comment]
#48 Решили не добавлять в словарь
