### ISSUE TITLE
Добавить "Associated/Static Methods"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#12]
"Associated methods (or "static" methods): these do not take self. Associated means "related to". They are written differently, using ::. String::from() is an associated method, and so is Vec::new(). You usually see associated methods used to create new variables."

**Comment by funkill** [comment]
"Ассоциированный (статический) метод". Отсылаю сюда https://github.com/rust-lang-ru/dictionary/issues/11#issuecomment-782819535

В официальной документации оно зовётся "ассоциированная функция"

**Comment by p0lunin** [comment]
Ассоциированная функция будет более правильным термином на обоих языках, так как метод это всегда функция, принимающее в качестве параметра self/this.
