### ISSUE TITLE
Дополнить "Generics" рядом с "Generic"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#15]
[Обобщённые типы](https://doc.rust-lang.ru/book/ch10-00-generics.html)

Для большего понимания, предлагаю добавить рядом термин в множественном числе, так как он часто используется в доках. Например: generic/generics - обощенный/обобщенные типы.

**Comment by ava57r** [comment]
известно, что `s` обозначает множественное число в английском.
Считаю, что добавлять не нужно отдельный перевод для этого
