### ISSUE TITLE
Добавить "Question Mark Operator"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#16]
"There is an even shorter way to deal with Result (and Option), shorter than match and even shorter than if let. It is called the "question mark operator", and is just ?. After a function that returns a result, you can add ?."

**Comment by p0lunin** [comment]
Оператор "вопрос"
Оператор "знак вопроса"
Можно попробовать оттолкнуться от семантики: 
Оператор "возврата"
Оператор "раннего возврата"

**Comment by blandger** [comment]
оператор распространения ошибки
по аналогии с 
propagating errors - распространение ошибок

**Comment by ava57r** [comment]
"?" Можно и для Option использовать когда функция возвращает Option.

**Comment by ava57r** [comment]
Это получается ранний возврат из функции
- по причине ошибки
- Если значение Option::None
