### ISSUE TITLE
Добавить "Panic"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#18]
"Rust has a panic! macro that you can use to make it panic. It is easy to use:"

**Comment by funkill** [comment]
Коряво, но можно примерно так
> В Rust есть макрос `panic!`, который вы можете использовать для создания паники. Он прост в использовании:

В trpl часто panic так и переводят как "паника" (н-р [тут](https://doc.rust-lang.ru/book/ch09-03-to-panic-or-not-to-panic.html))
