### ISSUE TITLE
Добавить перевод "lifetime variance"

### ISSUE THREAD

**Issue by ozkriff** [rust-lang-ru/dictionary#2]
И связанных терминов.

Встречается, например, в https://doc.rust-lang.org/nomicon/subtyping.html

Есть в 11й лекции Кладова: https://youtu.be/vz1_aRlF2TI?t=4707

**Comment by ava57r** [comment]
а вариант перевода есть?

**Comment by ava57r** [comment]
не могу придумать внятного перевода.

**Comment by ozkriff** [comment]
В джава книгах-статьях для variance встречается "вариативность" и "вариантность".

**Comment by ava57r** [comment]
То есть что такое "вариативность времён жизни"?

**Comment by ava57r** [comment]
@funkill @blandger @nlinker Как считаете?

**Comment by blandger** [comment]
Да, есть такое. Как "вариативность вр.ж." думаю норм.
