### ISSUE TITLE
Добавить "Derive"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#20]
"Now we want to print mr_mantle. Debug is easy to derive:"

**Comment by p0lunin** [comment]
В trpl это преимущественно переводится как "вывод" (например, здесь https://doc.rust-lang.ru/book/appendix-03-derivable-traits.html?highlight=Derive#%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%92-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4%D0%B8%D0%BC%D1%8B%D0%B5-%D1%82%D0%B8%D0%BF%D0%B0%D0%B6%D0%B8)

**Comment by funkill** [comment]
В статье про GLib наткнулся на интерпретацию `derive` как "генерируемый" или "наследуемый".

Если посмотреть [Appendix C: Derivable Traits](https://doc.rust-lang.org/book/appendix-03-derivable-traits.html?highlight=derive#appendix-c-derivable-traits)
> The `derive` attribute generates code that will implement a trait with its own default implementation on the type you’ve annotated with the `derive` syntax.

то как мне кажется, можно использовать в качестве перевода "генерация", "сгенерировать". Оно будет ближе и понятнее.

Как считаете?

**Comment by ava57r** [comment]
> Как считаете?

Согласен.
Выглядит такой перевод понятнее.

**Comment by ava57r** [comment]
#47 Изменили немного перевод
