### ISSUE TITLE
Trait

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/dictionary#22]
Возможные варианты: 
- типаж (текущий)
- черта
- трейт

**Comment by ivanych** [comment]
Я тут из мира Перла заглянул, так там это называется "роль" ("role"). Что-то вроде "этот объект играет роли такие-то...".

"Типаж" конечно сбивает с толку, особенно, если ранее с таким термином не сталкивался. "Трейт" понятен сходу, даже если в другом языке программирования это называлось как-то иначе, потому что англоязычная документация в основной своей массе использует термин "trate".

**Comment by SomeAkk** [comment]
В Scala так же имеет место быть понятие trait. Слава богу для Scala есть книжки на русском, в качестве примера можем взять ["Scala. Профессиональное программирование"](https://www.ozon.ru/context/detail/id/142588444/): в книге переводчиками издательства "Питер" trait переведен как "трейт". Мне импонирует данный термин переводить так же, как в издательствах - просто как "трейт".

Еще один аргумент за трейт заключается в том, что я хочу выбрать из двух бессмысленных в моей речи слов сразу базовое слово, а не какое-то дополнительное, которое привязано к базовому. 

> Поясню:
> trait -> читаю как трейт -> запоминаю как трейт - идеально для меня
> trait  -> читаю как трейт -> запоминаю как типаж - не идеально, т.к. в голове надо держать сразу два бессмысленных слова: трейт (которое известно так и в скале и в мире и много еще где) и типаж (которое не понятно кому за пределами rust ру-сообщества еще может быть известно).

**Comment by ava57r** [comment]
"трейт" - это же не перевод....

**Comment by funkill** [comment]
Чтобы посмотреть кто какой термин использует:

- ДМК-Пресс. Джим Блэнди "Программирование на языке Rust"  - [Харакеристика](https://www.litres.ru/static/or3/view/or.html?art_type=4&bname=%2525D0%25259F%2525D1%252580%2525D0%2525BE%2525D0%2525B3%2525D1%252580%2525D0%2525B0%2525D0%2525BC%2525D0%2525BC%2525D0%2525B8%2525D1%252580%2525D0%2525BE%2525D0%2525B2%2525D0%2525B0%2525D0%2525BD%2525D0%2525B8%2525D0%2525B5%252520%2525D0%2525BD%2525D0%2525B0%252520%2525D1%25258F%2525D0%2525B7%2525D1%25258B%2525D0%2525BA%2525D0%2525B5%252520Rust&trial=1&cover=%2Fstatic%2Fbookimages%2F53%2F66%2F64%2F53666407.bin.dir%2F53666407.cover.jpg&uuid=593d152d-ead2-11e9-a705-0cc47a520474&art=45670192&user=0) ("Глава 11. Характеристики и универсальные типы"). При этом они вводят термин "крейт" ("Глава 8. Крейты и модули")
- ИД Питер. С. Клабник "Программирование на Rust" (он же TRPL, который мы переводим) - [типаж](https://storage.piter.com/upload/contents/978544611656/978544611656_X.pdf). При этом, по всей видимости, термин "crate", они переводят как "упаковка".
- Официальная документация PHP - [трейт](https://www.php.net/manual/ru/language.oop5.traits.php)
- ИД Питер. М. Одерски. "Scala. Профессиональное программирование" - [Трейт](https://images.wbstatic.net/big/new/4730000/4734299-6.jpg), [ссылка на товар](https://www.wildberries.ru/catalog/4734299/detail.aspx)
- Wikipedia - [типаж](https://ru.m.wikipedia.org/wiki/%D0%A2%D0%B8%D0%BF%D0%B0%D0%B6_(%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D1%8B%D0%B9_%D1%82%D0%B8%D0%BF))

**Comment by funkill** [comment]
А еще не являются переводом такие слова, как «монитор», «парашют», «дисплей», «дизайн», «документ» (и следовательно «документация») и многие другие.
Думаю тут лучше осмысленно заимствовать слово, так как оно уже используется в сообществе и вроде как прижилось.

**Comment by ava57r** [comment]
Вот предположим приняли трайт. чего мне не хочется )

ринемся менять название везде специально, где встретим?

**Comment by funkill** [comment]
У нас впереди перевычитка всех книг, так что постепенно везде поменяем. А оставлять несогласованность терминов в рамках одной книги будет ухудшать качество. Ну и в любом случае при первом использовании укажем другие варианты перевода термина.

**Comment by ilyakmet** [comment]
Пусть будет Трейт

**Comment by p0lunin** [comment]
В целом, правильнее конечно называть растовские трейты тайпклассами (typeclasses), как они и называются в haskell. Но чтобы не возникало дробления с уже сложившейся экосистемой, лучше оставить типаж, на мой вкус.
1. Типаж - русское слово, имеющее совершенно приятное звучание и написание.
2. От этого слова могут возникнуть ассоциации, которые помогут осознать смысл сей конструкции.
3. В программировании типажи действительно есть https://ru.m.wikipedia.org/wiki/%D0%A2%D0%B8%D0%BF%D0%B0%D0%B6_(%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D1%8B%D0%B9_%D1%82%D0%B8%D0%BF), которые очень похожи на наши тайпклассы.

**Comment by ava57r** [comment]
Предлагаю так
В каждом языке есть
- литературный
- разговорный

Вот у нас так будет
- литературный - это ТИПАЖ
- разговорный - это ТРЕЙТ

**Comment by torgeek** [comment]
Исходя из [понимания авторов термина](http://scg.unibe.ch/archive/papers/Scha02bTraits.pdf), типажи (traits) — это композиция элементов поведения или общие черты поведения. По русски может быть так: черты поведения, манеры, нравы.

Вполне подходит слова «нрав», «манеры»: «унаследовал нрав ...», «реализовал манеры ...», «на манер ...», «манерность объекта», «нрав объекта ...». Вместо точек — имя/название типажа. 

Русское «типаж» в этом смысле несколько размывает исходный посыл черт поведения, указывая на любые черты или совокупность признаков. Хотя реализация в PHP под это размытие попадает точно))

**Comment by ilyakmet** [comment]
> Предлагаю так
> В каждом языке есть
> 
>     * литературный
> 
>     * разговорный
> 
> 
> Вот у нас так будет
> 
>     * литературный - это ТИПАЖ
> 
>     * разговорный - это ТРЕЙТ

Мы ведь пытаемся сделать текст доступным ждля понимания. Да ты прав. Но вариант с "трейт" точно никого не будет путать.

**Comment by ilyakmet** [comment]
> У нас впереди перевычитка всех книг, так что постепенно везде поменяем. А оставлять несогласованность терминов в рамках одной книги будет ухудшать качество. Ну и в любом случае при первом использовании укажем другие варианты перевода термина.

Вот кстати интересный момент:

```Let's look at the comparison to traits for generics again. For example:```

```
use std::fmt::Display;

fn prints<T: Display>(input: T) {
    println!("T is {}", input);
}

fn main() {}

```

И как я понимаю, к типажам слово trait не имеет никакого отношения в данном контексте. Так что автозамену по тексту не так просто будет сделать.

**Comment by ava57r** [comment]
принимаются оба варианта. на этом и закрою

**Comment by TheTharin** [comment]
По поводу слова **_Trait_** внесу свою лепту:

Есть же замечательное слово **_Черта_**. Более того, оно даже является прямым переводом. Дословно прямым переводом с английского, если отбросить "технический" аспект вопроса.
Почему нельзя было выбрать его?

> Типаж - Совокупность признаков (черт), в к-рых обнаруживается какой-н. тип.

Приведенное выше лексическое значение больше подходит к тому, что в Rust называется "**_Тип Type_**" (не даром это синоним). Цитата:

> Тип - это то, как интерпретируется значение в памяти и то, какие операции могут быть проведены над таким значением. 

Если переводить это на язык метафизический, то получится:

> Обобщение особенностей поведения и отображения сущности в отдельный тип. 

И тут же мы в переводе для слова **_Trait_** имеем слово **_Типаж_**, - _абсолютно созвучный синоним_ к слову **_Тип_** в русском языке, когда в Rust для слова **_Trait_** дается такое определение:

> A trait is a language feature that tells the Rust compiler about functionality a type must provide. 
Т.е.:
> Описание поведения какого-либо типа.

У **_Type_** может быть множество **_Trait_** , что коррелирует с лексическим значением слова Тип (совокупность особенностей).

Т.е. мы одновременно имеем два синонимичных _**И**_ созвучных слова (**_Тип_** и **_Типаж_**), только одно из них обозначает _Общность_ (совокупность поведений), а другое - _Частность_ (отдельно взятое поведение Типа).

Мне одному это кажется странным?

По поводу использования слова **_черта_** - не вижу никаких объективных предпосылок НЕ использовать это слово.

**Comment by star-ver** [comment]
Ежли зрить в корень, то:
**Type** - тип данных,
**Trait** - тип поведения.

"Типаж", "черта", "характеристика" - так себе варианты, поскольку смешивают в себе и то и то (данные и функционал), а надо бы четко отделять одно от другого. "Роль", на мой взгляд - наиболее адекватный перевод "трейт"а. _"Для типов Блоха, Заяц, Жеребец реализована роль Скакун"._ Но, всё же, использование слова Трейт "как есть" выглядит более предпочтительным. Оно вполне русское по звучанию и ближе к коду - то бишь, не требует доп. конвертации в уме а-ля "мы говорим - партия, подразумеваем - Ленин".

**Comment by star-ver** [comment]
Ещё один немаловажный для русскоговорящего человека момент. По-русски правильнее было бы писать не - "такой-то тип реализует такой то трейт" (ибо тип ничего не реализует, да и не могёт ничего реализовать), а: "для такого-то типа реализуется такой-то трейт". Это важно. Иначе получается - там неясность, тут неточность - и текст становится неудобоваримым. Тип не реализует поведение, но может _обладать_ поведением, для него реализованным.

**Comment by aleksandr-shevchenko** [comment]
Я за устоявшееся слово "трейт". В PHP сделали правильно, назвали трейт трейтом, многие лекторы по Rust(в частности Алексей Кладов), используют слово трейт. В данной книге тоже не надо выделываться и тоже использовать устоявшийся в программистской среде термин.
А то предлагают типа русский аналог и параллельно пишут в тексте "Вау", за что я бы отлучал от компа на месяц))).

**Comment by ava57r** [comment]
> Я за устоявшееся слово "трейт". В PHP сделали правильно, назвали трейт трейтом, многие лекторы по Rust(в частности Алексей Кладов), используют слово трейт. В данной книге тоже не надо выделываться и тоже использовать устоявшийся в программистской среде термин. А то предлагают типа русский аналог и параллельно пишут в тексте "Вау", за что я бы отлучал от компа на месяц))).

как вариант такой вариант допустим и внесён в dictionary уже

**Comment by kuzminrobin** [comment]
К сведенью:
В [Словаре для перевода](https://github.com/rust-lang-ru/dictionary) "trait" встречается дважды, причём первый случай стоИт не на своём месте (если сортировать по левой колонке по алфавиту).
"trait bounds" тоже не на своём месте.
