### ISSUE TITLE
Добавить "Type layout"

### ISSUE THREAD

**Issue by TelegaOvoshey** [rust-lang-ru/dictionary#33]
"We call any remaining invalid value a niche, and this space may be used for **type layout optimizations**"

Предлагаемый вариант: "схема размещения типов".

**Comment by p0lunin** [comment]
Из предлагаемого варианта не очевидно, что идёт речь о расположении байтов в памяти. Здесь type layout означает "расположение байтов в памяти для типа", где layout означает "расположение байтов в памяти". Не знаю, как подобрать русский однослойный вариант.

**Comment by kuzminrobin** [comment]
А чем не устраивает устоявшийся перевод "раскладка" для слова "layout"?
Type layout - раскладка типа (подобно Keyboard layout - раскладка клавиатуры)
