### ISSUE TITLE
Добавить "Control Flow"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#4]
1. [Control Flow](https://ru.qaz.wiki/wiki/Control_flow) - тут переводится как "Поток Управления".
2. [Ветвление (программирование)](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)) - тут используется термин "Условные операторы".

Вариант 2 кажется мне наиболее логичным и понятным.

**Comment by funkill** [comment]
Тогда уж лучше [Порядок выполнения](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA_%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F) ([англ](https://en.wikipedia.org/wiki/Control_flow))

**Comment by funkill** [comment]
Просто в control flow попадают и циклы, и генераторы, и корутины и прочее, а условные операторы - это по большей части if/else/match.

Против термина "условные операторы" ничего не имею против, но он подойдёт только для части операторов.

Из-за этого я за "порядок выполнения"/"поток управления"

**Comment by ilyakmet** [comment]
> Просто в control flow попадают и циклы, и генераторы, и корутины и прочее, а условные операторы - это по большей части if/else/match.
> 
> Против термина "условные операторы" ничего не имею против, но он подойдёт только для части операторов.
> 
> Из-за этого я за "порядок выполнения"/"поток управления"

Согласен. Именно это я и хотел услышать.

**Comment by ava57r** [comment]
За "поток управления"

**Comment by ava57r** [comment]
так остановились на потоке управления?
