### ISSUE TITLE
Поправить/дополнить "crate"/"package"

### ISSUE THREAD

**Issue by ozkriff** [rust-lang-ru/dictionary#5]
Из недавнего ревью перевода Сокобана:

> > наших зависимостей (или пакетов)
> 
> > dependent packages (or crates)
> 
> вот тут надо осторожно, кмк. потому что
> 
> * "крейт" (crate) - это единица компиляции, концепция уровня rustc (компилятора).
> * "пакет" (package) - это нечто, описываемое Cargo.toml и состоящее из 0, 1 или множества крейтов и/или рекурсивно вложенных пакетов, концепция уровня cargo (пакетного менеджера).
> 
> При этом, в разговорной речи "крейт" часто используется вместо "пакета", когда из контекста ясно, что речь именно о штуке описываемой Cargo.toml. Например, "я загрузил свой крейт на crates.io" - поскольку просто единицу компиляции без оборачивания в Cargo.toml нельзя загрузить в crates.io хранилище, тут нет неоднозначности.

**Comment by ava57r** [comment]
может добавим дополнителное поле "в контексте"?

**Comment by ava57r** [comment]
Колонка добавлена :) #19
