### ISSUE TITLE
Добавить "Interior mutability"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#51]
> **Interior mutability** means having a little bit of mutability on the inside. Remember how in Rust you need to use mut to change a variable? There are also some ways to change them without the word mut. This is because Rust has some ways to let you safely change values inside of a struct that is immutable. Each one of them follows some rules that make sure that changing the values is still safe.

**Comment by ava57r** [comment]
А перевод какой будем добавлять?
