### ISSUE TITLE
Добавить "RwLock"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#54]
> RwLock means "read write lock". It is like a Mutex but also like a RefCell.

**Comment by ilyakmet** [comment]
Скорее всего, тут никакого перевода быть не может, но все равно надо явно указать это в словаре, если мы хотим быть последовательными.

**Comment by funkill** [comment]
Хз на сколько нужно, так как это тип стандартной библиотеки и кмк должен быть выделен как код
