### ISSUE TITLE
Добавить "Match Guard"

### ISSUE THREAD

**Issue by ilyakmet** [rust-lang-ru/dictionary#6]

**Comment by SomeAkk** [comment]
в моем мире для guard нащупывается как предохранитель/сторож/ограничитель, т.е. какое-то существительное, действующее лицо, которое ограничивает/предохраняет. 

В случае с выражением match, получается что это какой-то "внутренний предохранитель/сторож для кейса в инструкции match, который тормозит выполнение кода кейса". Как вот одним словом перевести - я даже хз.

Но возможно мои размышления помогут.

**Comment by p0lunin** [comment]
Guard expressions - охранные выражения.
Match guard - охранное выражение в сопоставлении с образцом (?).

**Comment by blandger** [comment]
дополнительное условие (доп. условие if в конструкции ветки match)

**Comment by ava57r** [comment]
> Match guard - охранное выражение в сопоставлении с образцом (?).

мне нравится это
