### ISSUE TITLE
Перевод Statement и Operator

### ISSUE THREAD

**Issue by dluschan** [rust-lang-ru/dictionary#70]
Всем привет!
Читая русский перевод книги был удивлён каким-то "операторам", которые диковато смотрятся после C++ и Python.
Я совсем недавно учу язык Rust и не имею опыта разработки на нём, но у меня сложилось впечатление, что основные концепции в нём соответствуют таковым в языке C++ и термины, соответственно, тоже.
Открыл оригинал и обнаружил в нём все привычные термины: "Statement", "Expression" и "Operator".
Предлагаю обратиться к опыту перевода на русский язык небезызвестной книги Бьёрна Страуструпа "Язык программирования C++" — перевод с английского С. Анисимова и М. Кононова под редакцией Ф. Андреева и А. Ушакова, 2006 год. В частности, прошу обратить внимание на примечание, глава 6.3 "Инструкции", страница 174:
"Здесь возникает следующее затруднение, очень неприятное как для редактора (переводчиков) книги, так, вероятно, и для читателей. Используемый в оригинале термин «statement» часто переводится на русский язык как «оператор». Мы все привыкли, что for, if, case и т. д. - это операторы, что неверно (по крайней мере в контексте С++). Термином «оператор» (operator) обозначается присваивание (=), сложение (+) и т. д. Операторы могут быть замещены в пользовательском классе. Большинство операторов имеет возвращаемое значение. В связи с тем, что понятия «орегаtor» и «statement» в оригинале четко разделены, мы вынуждены сделать это и в переводе. Поэтому для перевода «statement» мы выбрали отдельный термин - «инструкция», который также достаточно распространен в русскоязычной литературе. Мы надеемся, что это не вызовет у читателей недоумения. Таким образом, for, if, case и т. д. - это инструкции, а не операторы. -- Примеч. ред"
Да, последующие издания того же Специального издания Страуструпа разучились переводить эти термины, но, блин, почему бы не продолжать называть термины последовательно непротиворечиво (правильно?)?
Предлагаю:
"statement" — "инструкция";
"expression" — "выражение";
"operator" — "оператор".
ЗЫ даже если открыть книжку Изучаем Python, 4-е издание — Марк Лутц — Перевод А. Киселева — Главный редактор А. Галунов, то никакой путаницы: программа состоит из инструкций, и так далее.

**Comment by funkill** [comment]
Про то, почему такой перевод: https://github.com/kgv/rust_book_ru/pull/14

**Comment by dluschan** [comment]
Спасибо, отписался по вашей ссылке почему нужно менять перевод. Прошу внести изменения в https://github.com/rust-lang-ru/dictionary/blob/master/README.adoc.

**Comment by ava57r** [comment]
там уже как 8 лет назад обсуждение завершено =)
Давайте тут уже думать

**Comment by dluschan** [comment]
>Есть спорные вещи.
>
>Долго думал, как называть statement и как - operator. В итоге решил опираться на термины, которые давали в университете и которые используются в K&R C (как первоисточник описания близкого по духу языка) - оператор и операция соответственно. Если есть предложения как сделать лучше - изменю.

Добрый день.
Считаю, что выбран неподходящий перевод терминов «Statement» и «Operator». Отсылка к K&R C, безусловно важна, но нужно понимать, что мы можем лишь оперировать к переводу этой книги на русский язык. У меня это «Перевод с английского и редакция В.Л. Бродового» издания 2009 года. Да, в нём переводчик говорит, что «Statement» — это «оператор», и тем привносит путаницу на многие годы вперёд. Однако, пора от неё избавляться.
Подозреваю, что на момент перевода этой книги на русский язык C++ был либо не существовал, либо не был распространён, либо с ним не был знаком переводчик. В таком случае, использование «Statement» — «оператор» в то время могло не выглядеть плохой идеей, потому что реализовывать свои операторы было не надо, но всё изменилось с распространением языка C++ ну или других языков, предоставляющих такую возможность. Вспомните, например, как вы определяете оператор сложения в своём классе на C++. И несмотря на то, что Rust для реализации операторов использует другой синтаксис, всё же следует придерживаться единой терминологии, не создающей противоречий в русском и английском языках.
Просмотрел книги по программированию в своей библиотеке: не меньше, чем в половине «statement» — «инструкция» и «operator» — «оператор». Среди них, помимо С++, Python также есть Pascal и JavaScript (Выразительный Javascript (2-е издание): Автор: Марейн Хавербек; Переводчик: Вячеслав Голованов).
В общем от порочной практики переводить Statement как оператор давно пора отказаться!
ЗЫ Даже в [https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch19-03-advanced-traits.md#параметры-обобщённого-типа-по-умолчанию-и-перегрузка-операторов](https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch19-03-advanced-traits.md#%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B-%D0%BE%D0%B1%D0%BE%D0%B1%D1%89%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D1%82%D0%B8%D0%BF%D0%B0-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E-%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2) «operator» уже переводится как «оператор».

**Comment by dluschan** [comment]
Ок. Конечно, давайте обсудим всё здесь.
Продублировал своё сообщение сюда.

**Comment by ava57r** [comment]
в целом перевести как вы предлагете можно.

**Comment by dluschan** [comment]
Отлично. Что для этого и кто должен сделать?)

**Comment by ava57r** [comment]
поправить файл с терминами в этом репозитарии и прислать PR.
Словарь для человеков, поэтому ни для какой автоматической проверки он не используется.

**Comment by ava57r** [comment]
влил #72
